// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: vault_system.proto

package vault_system

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_vault_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Record                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_vault_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDataRequest) GetData() *Record {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_vault_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_vault_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_vault_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_vault_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Record                `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDataRequest) Reset() {
	*x = SetDataRequest{}
	mi := &file_vault_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDataRequest) ProtoMessage() {}

func (x *SetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDataRequest.ProtoReflect.Descriptor instead.
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{6}
}

func (x *SetDataRequest) GetData() *Record {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_vault_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{7}
}

func (x *GetDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Record                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_vault_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{8}
}

func (x *GetDataResponse) GetData() *Record {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetListMetaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListMetaResponse) Reset() {
	*x = GetListMetaResponse{}
	mi := &file_vault_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMetaResponse) ProtoMessage() {}

func (x *GetListMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMetaResponse.ProtoReflect.Descriptor instead.
func (*GetListMetaResponse) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{9}
}

func (x *GetListMetaResponse) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          string                 `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_vault_system_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vault_system_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_vault_system_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDataRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

var File_vault_system_proto protoreflect.FileDescriptor

const file_vault_system_proto_rawDesc = "" +
	"\n" +
	"\x12vault_system.proto\x12\x05vault\x1a\x1bgoogle/protobuf/empty.proto\"T\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"6\n" +
	"\x11UpdateDataRequest\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.vault.RecordR\x04data\"A\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\">\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"3\n" +
	"\x0eSetDataRequest\x12!\n" +
	"\x04data\x18\x02 \x01(\v2\r.vault.RecordR\x04data\"$\n" +
	"\x0eGetDataRequest\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta\"4\n" +
	"\x0fGetDataResponse\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.vault.RecordR\x04data\")\n" +
	"\x13GetListMetaResponse\x12\x12\n" +
	"\x04data\x18\x01 \x03(\tR\x04data\"'\n" +
	"\x11DeleteDataRequest\x12\x12\n" +
	"\x04meta\x18\x02 \x01(\tR\x04meta2\xb5\x03\n" +
	"\vVaultSystem\x12;\n" +
	"\bRegister\x12\x16.vault.RegisterRequest\x1a\x17.vault.RegisterResponse\x122\n" +
	"\x05Login\x12\x13.vault.LoginRequest\x1a\x14.vault.LoginResponse\x128\n" +
	"\aSetData\x12\x15.vault.SetDataRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\aGetData\x12\x15.vault.GetDataRequest\x1a\x16.vault.GetDataResponse\x12>\n" +
	"\n" +
	"DeleteData\x12\x18.vault.DeleteDataRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\n" +
	"UpdateData\x12\x18.vault.UpdateDataRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vGetListMeta\x12\x16.google.protobuf.Empty\x1a\x1a.vault.GetListMetaResponseB\x10Z\x0e./vault_systemb\x06proto3"

var (
	file_vault_system_proto_rawDescOnce sync.Once
	file_vault_system_proto_rawDescData []byte
)

func file_vault_system_proto_rawDescGZIP() []byte {
	file_vault_system_proto_rawDescOnce.Do(func() {
		file_vault_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vault_system_proto_rawDesc), len(file_vault_system_proto_rawDesc)))
	})
	return file_vault_system_proto_rawDescData
}

var file_vault_system_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vault_system_proto_goTypes = []any{
	(*Record)(nil),              // 0: vault.Record
	(*UpdateDataRequest)(nil),   // 1: vault.UpdateDataRequest
	(*RegisterRequest)(nil),     // 2: vault.RegisterRequest
	(*RegisterResponse)(nil),    // 3: vault.RegisterResponse
	(*LoginRequest)(nil),        // 4: vault.LoginRequest
	(*LoginResponse)(nil),       // 5: vault.LoginResponse
	(*SetDataRequest)(nil),      // 6: vault.SetDataRequest
	(*GetDataRequest)(nil),      // 7: vault.GetDataRequest
	(*GetDataResponse)(nil),     // 8: vault.GetDataResponse
	(*GetListMetaResponse)(nil), // 9: vault.GetListMetaResponse
	(*DeleteDataRequest)(nil),   // 10: vault.DeleteDataRequest
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_vault_system_proto_depIdxs = []int32{
	0,  // 0: vault.UpdateDataRequest.data:type_name -> vault.Record
	0,  // 1: vault.SetDataRequest.data:type_name -> vault.Record
	0,  // 2: vault.GetDataResponse.data:type_name -> vault.Record
	2,  // 3: vault.VaultSystem.Register:input_type -> vault.RegisterRequest
	4,  // 4: vault.VaultSystem.Login:input_type -> vault.LoginRequest
	6,  // 5: vault.VaultSystem.SetData:input_type -> vault.SetDataRequest
	7,  // 6: vault.VaultSystem.GetData:input_type -> vault.GetDataRequest
	10, // 7: vault.VaultSystem.DeleteData:input_type -> vault.DeleteDataRequest
	1,  // 8: vault.VaultSystem.UpdateData:input_type -> vault.UpdateDataRequest
	11, // 9: vault.VaultSystem.GetListMeta:input_type -> google.protobuf.Empty
	3,  // 10: vault.VaultSystem.Register:output_type -> vault.RegisterResponse
	5,  // 11: vault.VaultSystem.Login:output_type -> vault.LoginResponse
	11, // 12: vault.VaultSystem.SetData:output_type -> google.protobuf.Empty
	8,  // 13: vault.VaultSystem.GetData:output_type -> vault.GetDataResponse
	11, // 14: vault.VaultSystem.DeleteData:output_type -> google.protobuf.Empty
	11, // 15: vault.VaultSystem.UpdateData:output_type -> google.protobuf.Empty
	9,  // 16: vault.VaultSystem.GetListMeta:output_type -> vault.GetListMetaResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_vault_system_proto_init() }
func file_vault_system_proto_init() {
	if File_vault_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vault_system_proto_rawDesc), len(file_vault_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vault_system_proto_goTypes,
		DependencyIndexes: file_vault_system_proto_depIdxs,
		MessageInfos:      file_vault_system_proto_msgTypes,
	}.Build()
	File_vault_system_proto = out.File
	file_vault_system_proto_goTypes = nil
	file_vault_system_proto_depIdxs = nil
}
