// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: vault_system.proto

package vault_system

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultSystem_Register_FullMethodName    = "/vault.VaultSystem/Register"
	VaultSystem_Login_FullMethodName       = "/vault.VaultSystem/Login"
	VaultSystem_SetData_FullMethodName     = "/vault.VaultSystem/SetData"
	VaultSystem_GetData_FullMethodName     = "/vault.VaultSystem/GetData"
	VaultSystem_DeleteData_FullMethodName  = "/vault.VaultSystem/DeleteData"
	VaultSystem_UpdateData_FullMethodName  = "/vault.VaultSystem/UpdateData"
	VaultSystem_GetListMeta_FullMethodName = "/vault.VaultSystem/GetListMeta"
)

// VaultSystemClient is the client API for VaultSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaultSystemClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetListMeta(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListMetaResponse, error)
}

type vaultSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultSystemClient(cc grpc.ClientConnInterface) VaultSystemClient {
	return &vaultSystemClient{cc}
}

func (c *vaultSystemClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, VaultSystem_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, VaultSystem_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VaultSystem_SetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, VaultSystem_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VaultSystem_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VaultSystem_UpdateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultSystemClient) GetListMeta(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetListMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListMetaResponse)
	err := c.cc.Invoke(ctx, VaultSystem_GetListMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultSystemServer is the server API for VaultSystem service.
// All implementations must embed UnimplementedVaultSystemServer
// for forward compatibility.
type VaultSystemServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	SetData(context.Context, *SetDataRequest) (*emptypb.Empty, error)
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	DeleteData(context.Context, *DeleteDataRequest) (*emptypb.Empty, error)
	UpdateData(context.Context, *UpdateDataRequest) (*emptypb.Empty, error)
	GetListMeta(context.Context, *emptypb.Empty) (*GetListMetaResponse, error)
	mustEmbedUnimplementedVaultSystemServer()
}

// UnimplementedVaultSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultSystemServer struct{}

func (UnimplementedVaultSystemServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedVaultSystemServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedVaultSystemServer) SetData(context.Context, *SetDataRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetData not implemented")
}
func (UnimplementedVaultSystemServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedVaultSystemServer) DeleteData(context.Context, *DeleteDataRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedVaultSystemServer) UpdateData(context.Context, *UpdateDataRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateData not implemented")
}
func (UnimplementedVaultSystemServer) GetListMeta(context.Context, *emptypb.Empty) (*GetListMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListMeta not implemented")
}
func (UnimplementedVaultSystemServer) mustEmbedUnimplementedVaultSystemServer() {}
func (UnimplementedVaultSystemServer) testEmbeddedByValue()                     {}

// UnsafeVaultSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultSystemServer will
// result in compilation errors.
type UnsafeVaultSystemServer interface {
	mustEmbedUnimplementedVaultSystemServer()
}

func RegisterVaultSystemServer(s grpc.ServiceRegistrar, srv VaultSystemServer) {
	// If the following call panics, it indicates UnimplementedVaultSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultSystem_ServiceDesc, srv)
}

func _VaultSystem_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_SetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_UpdateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).UpdateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_UpdateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).UpdateData(ctx, req.(*UpdateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultSystem_GetListMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultSystemServer).GetListMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultSystem_GetListMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultSystemServer).GetListMeta(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultSystem_ServiceDesc is the grpc.ServiceDesc for VaultSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vault.VaultSystem",
	HandlerType: (*VaultSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _VaultSystem_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _VaultSystem_Login_Handler,
		},
		{
			MethodName: "SetData",
			Handler:    _VaultSystem_SetData_Handler,
		},
		{
			MethodName: "GetData",
			Handler:    _VaultSystem_GetData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _VaultSystem_DeleteData_Handler,
		},
		{
			MethodName: "UpdateData",
			Handler:    _VaultSystem_UpdateData_Handler,
		},
		{
			MethodName: "GetListMeta",
			Handler:    _VaultSystem_GetListMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vault_system.proto",
}
